# Simple Imputer

It replaces missing values (like NaNs) with a chosen statistical measure,
such as the column's mean, median, most frequent value, or a constant.

For Numerical values


In [1]:
import pandas as pd
import numpy as np
from pandas.conftest import axis

data = {
    "Age": [22, 25, np.nan, 30, 28, np.nan, 35, 24],
    "Salary": [40000, 50000, 45000, np.nan, 60000, 52000, np.nan, 48000],
    "Experience": [1, 3, 2, 5, np.nan, 4, 7, np.nan],

}

df = pd.DataFrame(data)

print(df)

    Age   Salary  Experience
0  22.0  40000.0         1.0
1  25.0  50000.0         3.0
2   NaN  45000.0         2.0
3  30.0      NaN         5.0
4  28.0  60000.0         NaN
5   NaN  52000.0         4.0
6  35.0      NaN         7.0
7  24.0  48000.0         NaN


In [2]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
df  = pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns
)

print(df)


    Age   Salary  Experience
0  22.0  40000.0         1.0
1  25.0  50000.0         3.0
2  26.5  45000.0         2.0
3  30.0  49000.0         5.0
4  28.0  60000.0         3.5
5  26.5  52000.0         4.0
6  35.0  49000.0         7.0
7  24.0  48000.0         3.5


For Categorical Values

In [3]:
import pandas as pd
import numpy as np

data = {
    "City": ["Karachi", "Lahore", np.nan, "Karachi", "Islamabad",
             "Lahore", np.nan, "Karachi"],
    "Purchased": ["Yes", "No", "Yes", "No", np.nan, "Yes", "No", "Yes"]
}

print(df.isnull().sum())

df = pd.DataFrame(data)

print(df)

Age           0
Salary        0
Experience    0
dtype: int64
        City Purchased
0    Karachi       Yes
1     Lahore        No
2        NaN       Yes
3    Karachi        No
4  Islamabad       NaN
5     Lahore       Yes
6        NaN        No
7    Karachi       Yes


In [4]:
from sklearn.impute import SimpleImputer

C_imputer = SimpleImputer(strategy='most_frequent')

df = pd.DataFrame(
    C_imputer.fit_transform(df),
    columns=df.columns
)

print(df)

        City Purchased
0    Karachi       Yes
1     Lahore        No
2    Karachi       Yes
3    Karachi        No
4  Islamabad       Yes
5     Lahore       Yes
6    Karachi        No
7    Karachi       Yes


When both numerical and categorical comes in a single dataset

In [5]:
data = {
    "Age": [22, 25, np.nan, 30],
    "Salary": [40000, np.nan, 50000, 60000],
    "City": ["Karachi", "Lahore", np.nan, "Karachi"]
}

for key,value  in data.items():
    print(key,value)

df = pd.DataFrame(data)

Age [22, 25, nan, 30]
Salary [40000, nan, 50000, 60000]
City ['Karachi', 'Lahore', nan, 'Karachi']


In [6]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

num_cols = ['Age','Salary']
cat_cols = ['City']

preprocessor = ColumnTransformer(
    [
        ('num_imputer',SimpleImputer(strategy='median'),num_cols),
        ('cat_imputer',SimpleImputer(strategy='most_frequent'),cat_cols)
    ]
)

result = preprocessor.fit_transform(df)

print(result)

[[22.0 40000.0 'Karachi']
 [25.0 50000.0 'Lahore']
 [25.0 50000.0 'Karachi']
 [30.0 60000.0 'Karachi']]


# One Label-Encoder

LabelEncoder is a scikit-learn utility that converts categorical text labels into numerical integer values (e.g., 0, 1, 2) within a single column.

In [7]:
import pandas as pd

data = {
    "Study_Hours": [2, 5, 3, 7, 4, 6],
    "Result": ["Fail", "Pass", "Fail", "Pass", "Fail", "Pass"]
}

df = pd.DataFrame(data)



In [8]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['Result'] = label_encoder.fit_transform(df['Result'])

print(df)

   Study_Hours  Result
0            2       0
1            5       1
2            3       0
3            7       1
4            4       0
5            6       1


# One Hot-Encoder

OneHotEncoder is a scikit-learn preprocessing tool that converts categorical data (like text labels) into a binary matrix format.

It creates a new binary column (containing 0s or 1s) for each unique category, preventing machine learning models from incorrectly assuming a natural ranking or mathematical order among the categories.

In [9]:
import pandas as pd

data = {
    "Age": [22, 25, 30, 28, 11, 80],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad","Peshawar","Quetta"]
}

for keys,name in data.items():
    print(keys,name)

df = pd.DataFrame(data)

Age [22, 25, 30, 28, 11, 80]
City ['Karachi', 'Lahore', 'Karachi', 'Islamabad', 'Peshawar', 'Quetta']


In [10]:
from sklearn.preprocessing import OneHotEncoder

hot_encoder = OneHotEncoder(sparse_output=False)

encoded = hot_encoder.fit_transform(df[['City']])

df[hot_encoder.get_feature_names_out(['City'])]  = encoded

df.drop(columns=['City'],inplace=True)

print(df)

   Age  City_Islamabad  City_Karachi  City_Lahore  City_Peshawar  City_Quetta
0   22             0.0           1.0          0.0            0.0          0.0
1   25             0.0           0.0          1.0            0.0          0.0
2   30             0.0           1.0          0.0            0.0          0.0
3   28             1.0           0.0          0.0            0.0          0.0
4   11             0.0           0.0          0.0            1.0          0.0
5   80             0.0           0.0          0.0            0.0          1.0


# Standard Scalar(Standardization)

Centers the average at zero and evens the spread.

Best Used When...
Data has no strict limits, and no massive outliers.


In [15]:
import numpy as np
from sklearn.preprocessing import StandardScaler

data = np.array([
              [25,50000],
              [35,75000],
              [45,1000000]])

scalar = StandardScaler()

X_scaled = scalar.fit_transform(data)

print("Original data:\n",data)
print("Scaled data:\n",X_scaled)


Original data:
 [[     25   50000]
 [     35   75000]
 [     45 1000000]]
Scaled data:
 [[-1.22474487 -0.73519503]
 [ 0.         -0.67864156]
 [ 1.22474487  1.41383659]]


# Min-Max Scaler (Normalization)

Squishes data into a strict, rigid box.

Best Used When...
Data has absolute natural limits (like 0-100 test marks).

In [18]:
import  numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([[2,45],
                 [6,78],
                 [12,92]
                 ])

scalar = MinMaxScaler()

X_scaled = scalar.fit_transform(data)

print("orignal data : \n",data)
print("Scaled data: \n",X_scaled)

orignal data : 
 [[ 2 45]
 [ 6 78]
 [12 92]]
Scaled data: 
 [[0.         0.        ]
 [0.4        0.70212766]
 [1.         1.        ]]


# Robust Scaler(Robust Scaling)

Balances data using the middle number, ignoring extremes.

Best Used When...Data contains massive, extreme outliers (like a billionaire).


In [20]:
import numpy as np
from sklearn.preprocessing import RobustScaler

data = np.array([[50000],
                 [60000],
                 [70000],
                 [800000000]])

scalar = RobustScaler()
X_scaled = scalar.fit_transform(data)

print("Original Data: \n",data)
print("Scaled Data: \n",X_scaled)


Original Data: 
 [[    50000]
 [    60000]
 [    70000]
 [800000000]]
Scaled Data: 
 [[-7.50018750e-05]
 [-2.50006250e-05]
 [ 2.50006250e-05]
 [ 3.99977499e+00]]
